Fix tests
assertEquals is deprecated, use assertEqual.

Remove assert that consistently fails with

AssertionError: assert 5 == 'Mock file descriptor'

Signed-off-by: Michal Suchanek <msuchanek@suse.de>